// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBezhh83RIqeYRsKglC_mCD8weHo3RS-Hg',
    appId: '1:36171729550:web:574e358cc6b390b4e357df',
    messagingSenderId: '36171729550',
    projectId: 'orbly-619bf',
    authDomain: 'orbly-619bf.firebaseapp.com',
    storageBucket: 'orbly-619bf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqJdHb1YQ3Z58A_SuQ2mRD1L0DYFnELdk',
    appId: '1:36171729550:android:c0c6ce6c155052e4e357df',
    messagingSenderId: '36171729550',
    projectId: 'orbly-619bf',
    storageBucket: 'orbly-619bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr5WG2JbE2mjmeGqkVe1XWWHDYjBeP26M',
    appId: '1:36171729550:ios:3a47b90f31fd5d56e357df',
    messagingSenderId: '36171729550',
    projectId: 'orbly-619bf',
    storageBucket: 'orbly-619bf.firebasestorage.app',
    iosBundleId: 'com.example.orbly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr5WG2JbE2mjmeGqkVe1XWWHDYjBeP26M',
    appId: '1:36171729550:ios:3a47b90f31fd5d56e357df',
    messagingSenderId: '36171729550',
    projectId: 'orbly-619bf',
    storageBucket: 'orbly-619bf.firebasestorage.app',
    iosBundleId: 'com.example.orbly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBezhh83RIqeYRsKglC_mCD8weHo3RS-Hg',
    appId: '1:36171729550:web:1dcbc9057c5b19cde357df',
    messagingSenderId: '36171729550',
    projectId: 'orbly-619bf',
    authDomain: 'orbly-619bf.firebaseapp.com',
    storageBucket: 'orbly-619bf.firebasestorage.app',
  );
}
